version: "2"

services:
  mysqlDB:
    image: mysql:8.0.22
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: ${CONTAINER_NAME}
    hostname: ${HOSTNAME}
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    environment:
      LANG: es_ES.UTF-8
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8844:3306"
    volumes:
      - ./mysqldb:/var/lib/mysql
    restart: always

    networks:
      - php-network-nameproject

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8822:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - php-network-nameproject

  memcached:
    image: memcached
    container_name: memcached
    hostname: memcached
    expose:
      - 11211
      
  web:
    image: nginx:latest
    ports:
      - "8899:80"
    volumes:
      - ./apps:/apps
      - ./logs/nginx:/logs/nginx
      - ./config/nginx/xdebug:/etc/nginx/xdebug
      - ./config/nginx/hosts:/etc/nginx/hosts
      - ./config/nginx/init.conf:/etc/nginx/conf.d/default.conf
    networks:
      - php-network-nameproject

  php:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./apps:/apps
      - ./logs/xdebug:/logs/xdebug
      - ./config/php/custom.conf:/usr/local/etc/php-fpm.d/zz-custom.conf
      - ./config/php/xdebug.ini:/usr/local/etc/php/conf.d/zz-xdebug.ini
      - ./logs/php-fpm/:/tmp/xdebug_log
      - ./config/php/php-custom.ini:/usr/local/etc/php/conf.d/memory_limit.ini
    networks:
      - php-network-nameproject

networks:
  php-network-nameproject:
    driver: bridge
